[package]
name = "day-two"  # https://adventofcode.com/2023/day/2
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = "1.37.0"
nom = "7.1.3"
